config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/dialogs/:id', to: 'dialogs#show', as: :user

  resources :dialogs, only: [:index, :show] do
    resources :messages, only: :create
  end

  root 'dialogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  alias_attribute :dialog_id, :receiver_id

  validates :text, presence: true, length: { minimum: 1 }

  def self.get_dialog(sender, receiver)
    where(sender_id: sender.id, receiver_id: receiver.id)
      .or(where(sender_id: receiver.id, receiver_id: sender.id))
      .includes(:sender, :receiver)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
  has_many :received_messages, class_name: 'Message', foreign_key: 'receiver_id'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:vkontakte]

  validates :uid, presence: true

  def self.from_vk(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = "#{auth.uid}@vk.com"
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def require_signed_in
    unless user_signed_in?
      redirect_to(dialogs_path, flash: { sign_up_warning: t('.sign_up_warning') })
    end
  end
end

app/controllers/dialogs_controller.rb
class DialogsController < ApplicationController
  before_action :require_signed_in, only: :show

  def index
    @users = User.all
  end

  def show
      @receiver = User.find(params[:id])
      @dialog = Message.get_dialog(
        current_user, @receiver).map { |msg| MessageSerializer.new(msg).attributes }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_signed_in, only: :create

  def create
    message = Message.new(message_params)
    message.sender_id = current_user.id

    if message.save
      receiver = User.find_by_id(message.receiver_id)
      broadcast_message_data = build_brodcast_message_data(message, receiver)

      # Don't have an essence of dialog, so broadcast the both channels
      ActionCable.server.broadcast("messages_#{message.sender_id}_#{receiver.id}", broadcast_message_data)
      ActionCable.server.broadcast("messages_#{receiver.id}_#{message.sender_id}",
        broadcast_message_data) unless message.sender_id == receiver.id
    else
      redirect_to dialogs_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:text, :receiver_id)
      .merge(params.permit(:dialog_id))
  end

  def build_brodcast_message_data(message, receiver)
    {
        id: message.id,
        sender: current_user.name,
        receiver: receiver.name,
        sender_id: current_user.id,
        receiver_id: message.receiver_id,
        text: message.text,
        created_at: message.created_at
    }
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def vkontakte
    @user = User.from_vk(request.env['omniauth.auth'])

    sign_in_and_redirect @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dialogs_helper.rb
module DialogsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/dialogs/_users.html.haml
.col-xs-8.col-md-offset-2
  %h3 Dialogs
  = render 'layouts/notification'
  %ul.list-group
    - locals[:users].each do |user|
      %li.list-group-item
        = link_to(user.name, user)

app/views/dialogs/index.html.haml
= render 'users', locals: { users: @users }

app/views/dialogs/show.html.haml
.col-xs-8.col-md-offset-2
  %h4 Dialog with #{@receiver.name}
  = react_component('Dialog', messages: @dialog, sender_id: current_user.id, receiver_id: @receiver.id)
  = render 'messages/form', locals: { receiver: @receiver }

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      = link_to 'Chat', dialogs_path, class: 'navbar-brand'
    .collapse.navbar-collapse.navbar-ex1-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %p.navbar-text Signed in as #{current_user.name}
          %li= link_to 'Sign out', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Sign up from VK', user_vkontakte_omniauth_authorize_path

app/views/layouts/_notification.html.haml
- if flash[:sign_up_warning]
  .alert.alert-warning{role: 'alert'}
    %span.glyphicon.glyphicon-exclamation-sign{'aria-hidden' => 'true'}
    =flash[:sign_up_warning]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Chat
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/navbar'
    .container.jumbotron
      .row
        = yield

app/views/messages/_form.html.haml
= form_for :message, url: dialog_messages_path(locals[:receiver]),
    remote: true, authenticity_token: true, html: { class: 'form-group', id: 'message-form' } do |f|
  = f.text_area :text, placeholder: 'Enter your message here...', class: 'form-control', data: { textarea: 'message' }
  = f.submit 'Send', id: 'submit-form-el', class: 'btn btn-primary',  data: { send: 'message' }